name: Build and Test

on: 
  push:
    branches: [main]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install selenium
      run: pip install selenium
      
    - name: Run tests
      run: python -m unittest discover tests >> echo
      #run: echo $1 >> "$GITHUB_OUTPUT"

    - name: send default message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
