name: Build and Test

on: 
  push:
    branches: [main]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Discover server
      run: pwd && ls -lah
      
    - name: Run tests
      run: python3 -m unittest discover tests >> $GITHUB_OUTPUT >> output.txt
      #run: echo $1 >> "$GITHUB_OUTPUT"

    - name: send default message
      uses: appleboy/telegram-action@master
      
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: output.txt
      env:
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      
        
